[package]
name = "server"
version = "0.1.0"
authors = ["Allison Knauss <piper.pandemos@gmail.com>"]
edition = "2018"

[dependencies]
util = { path = "../util" }
aaa = { path = "../aaa" }
telemetry = { path = "../telemetry" }
router = { path = "../router" }
