[package]
name = "util"
version = "0.1.0"
authors = ["Allison Knauss <piper.pandemos@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.9"
tokio = "*"
tokio-postgres = "*"
refinery = { version = "0.3", features = ["tokio-postgres"] }
