[package]
name = "aaa"
version = "0.1.0"
authors = ["Allison Knauss <piper.pandemos@gmail.com>"]
edition = "2018"

[dependencies]
jsonwebtoken = "7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
util = { path = "../util" }
